spring.application.name=chat_app
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username= tata
spring.datasource.password= Merutan68
spring.flyway.baselineOnMigrate=true